data = {
    "responseHeader": {
    "status": 0,
        "QTime": 17
},
    "response": {
    "numFound": 464278,
        "start": 0,
        "docs": [
        {
            "id": "684325",
            "url": "/news/2015/0304/684325-boston-marathon-bombings/",
            "content": "<p>A lawyer for the accused Boston marathon bomber has said that their client bore responsibility for the attacks that killed three people and injured 264 with a blunt admission: &quot;It was him.&quot;</p>\r\n<p>However, Dzhokhar Tsarnaev was a secondary player in the 15 April&nbsp;2013 bombings, defence attorney Judith Clarke said in her opening argument in US District Court in Boston.</p>\r\n<p>At the start of the trial, she indicated that the 21-year-old&#39;s older brother, Tamerlan, was the prime mover.</p>\r\n<p>The defence strategy, which did not include a move to change Mr Tsarnaev&#39;s not-guilty plea, appeared aimed at sparing him from the death penalty.</p>\r\n<p>If he is convicted, the jury will decide whether he is executed or gets life in prison without possibility of parole.</p>\r\n<p>Prosecutor&nbsp;William Weinreb&nbsp;told jurors how Mr Tsarnaev and his brother, both ethnic Chechens, carefully selected the places where they left the bombs in an effort to punish the United States for military actions in Muslim-dominated countries.</p>\r\n<p><img alt=\"\" src=\"https://img.rasset.ie/000a3f14-614.jpg\" /></p><p></p><p><a href=\"http://www.rte.ie/news/special-reports/2015/0304/684523-timeline-arrest-of-boston-bombing-suspect/\"><strong>Timeline - Arrest of Dzhokhar Tsarnaev</strong></a></p>\r\n<p>Assistant US Attorney Weinreb anticipated the defence&#39;s strategy of casting blame on 26-year-old Tamerlan Tsarnaev, who was killed when his younger brother inadvertently ran him over after a gun battle with police a few days after the bombing.</p>\r\n<p>&quot;The focus is going to be on the defendant,&quot; the prosecutor said.</p>\r\n<p>&quot;That&#39;s because it&#39;s his day in court. He&#39;s the one the government has to prove guilty, not his brother.&quot;</p>\r\n<p>However, Ms Clarke said although Dzhokhar Tsarnaev, then 19, set off a homemade pressure-cooker bomb at the marathon&#39;s crowded finish line and three days later participated in the fatal shooting of the police officer did not tell the whole story.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>\r\n<p>&quot;If the only question was whether that was Dzhokhar Tsarnaev... it would be very easy for you.&quot;</p>\r\n<p>She said her client played a secondary role in a scheme hatched and driven by his older brother.</p>\r\n<p>&quot;It was Tamerlan Tsarnaev who self-radicalised. It was Dzhokhar who followed him,&quot; Ms Clarke said.</p>\r\n<p>&quot;The evidence will show that Tamerlan planned and orchestrated and enlisted his brother into this series of horrific acts.&quot;</p>\r\n<p>The approach set up an immediate conflict with US District Judge George O&#39;Toole.</p>\r\n<p>He ruled shortly before opening statements that the question of the relative culpability of the two brothers was best left to the trial&#39;s second phase, which would follow providing Dzhokhar is found guilty.</p>\r\n<p>&quot;Some evidence of the brother&#39;s interactions will be inevitable,&quot; Judge O&#39;Toole allowed in brief remarks before the trial opened.</p>\r\n<p>However he interrupted Ms Clarke several times to warn her against going too deep into family history so early in the trial.</p>\r\n<p>In his argument, Mr Weinreb said that Dzhokhar had read radical online magazines, where he learned how to build the shrapnel-filled bombs that tore the legs off of about 16 people at the race&#39;s crowded finish line.</p>\r\n<p>&quot;He believed that he was a soldier in a holy war against Americans,&quot; Mr Weinreb said of Tsarnaev.</p>\r\n<p>The prosecutor also stressed the brutal nature of the injuries caused by the pressure-cooker bombs.</p>\r\n<p>&quot;The purpose of that kind of bomb is to shred flesh, shatter bone, set people on fire and cause people to suffer painful deaths,&quot; said Mr Weinreb.</p>\r\n<p><img alt=\"\" src=\"https://img.rasset.ie/00074054-614.jpg\" /></p>\r\n<p>He described the final moments of the three who died: restaurant manager Krystle Campbell, 29; graduate student Lingzi Lu, 23, and eight-year-old Martin Richard.</p>\r\n<p>He noted that Tsarnaev left the backpack he carried the bomb in behind a group of child spectators, including Martin.</p>\r\n<p>&quot;He pretended to be a spectator but he had murder in his heart,&quot; Mr Weinreb said.</p>\r\n<p>A dozen or so people injured in the attack and family members, including dancer Heather Abbott and Marc Fucarile, both of whom lost legs in the blasts, and Martin&#39;s parents, were in court during the proceedings.</p>\r\n<p>The jury saw several videos of the bombs going off and of badly injured people screaming on the ground, surrounded by bits of metal shrapnel and thick smoke.</p>\r\n<p>&quot;I was blown through the air. There was a deafening explosion,&quot; said Colton Kilgore, who had travelled from Asheville, North Carolina, to see his mother-in-law race.</p>\r\n<p>&quot;As I was sitting up my brain was in this haze and I couldn&#39;t hear out of my left ear and there was screaming and I realised ... it must have been a bomb.&quot;</p>",
            "title": "Boston accused's lawyer tells trial: 'It was him'",
            "headline": "Boston accused's lawyer tells trial: 'It was him'",
            "type": "article",
            "sub_type": "newsdocument",
            "date_created": "2015-03-04T06:14:24Z",
            "date_modified": "2015-03-04T22:09:47Z",
            "excerpt": "A lawyer for the accused Boston marathon bomber has said that their client bore responsibility for the attacks that killed three people and injured 264 with a blunt admission: \"It was him.\"",
            "pillar": "News",
            "categories": "News, World, Crime and Legal",
            "keywords": "boston bombings, boston marathon",
            "images": "[{\"id\":\"000a3f0a\",\"caption\":\"Thousands paid tribute to the victims in the days following the bombings\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f0a-60.jpg\"},{\"id\":\"000a3f13\",\"caption\":\"A file image of Dzhokhar Tsarnaev, who faces 30 charges in relation to the bombings\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f13-60.jpg\"},{\"id\":\"000a3f0c\",\"caption\":\"Media gather outside the John Joseph Moakley United States Courthouse, as jury selection takes place\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f0c-60.jpg\"},{\"id\":\"000a3f0b\",\"caption\":\"The FBI released this image of  brothers Dzhokhar (L) and Tamerlan (R) at the Boston marathon on 15 April 2013\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f0b-60.jpg\"},{\"id\":\"000a402b\",\"caption\":\"Media wait outside the Boston courthouse\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a402b-60.jpg\"},{\"id\":\"000a402c\",\"caption\":\"Members of Dzhokhar Tsarnaev's defence team (L-R) David Bruck, Miriam Conrad and Judith Clarke\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a402c-60.jpg\"}]",
            "media": "[{\"id\":\"20738216\",\"type\":\"video\",\"caption\":\"Boston bombing suspect's lawyer says 'It was him'\",\"description\":\"\",\"programme\":\"Nine News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20738216\",\"duration\":227422,\"thumbnail_refcode\":\"000a4075\"},{\"id\":\"20737955\",\"type\":\"video\",\"caption\":\"Boston marathon bombing trial to get under way\",\"description\":\"\",\"programme\":\"One News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20737955\",\"duration\":35629,\"thumbnail_refcode\":\"000a3faa\"},{\"id\":\"20738216\",\"type\":\"video\",\"caption\":\"Boston bombing suspect admits he carried out the attacks\",\"description\":\"\",\"programme\":\"Nine News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20738216\",\"duration\":227422,\"thumbnail_refcode\":\"000a4075\"}]",
            "live_listing": "[]",
            "posts": "[]",
            "thumbnail_refcode": "000a3f0a",
            "thumbnail_caption": "Thousands paid tribute to the victims in the days following the bombings",
            "allow_ads": "true",
            "allow_comments": "false",
            "safe_ads": "false",
            "byline_binder_id": 0,
            "default_index_name": "News",
            "media_count": 3,
            "rank_news": 1,
            "highest_rank": 1,
            "rank_world": 1,
            "rank_crime-and-legal": 1,
            "media_id": 20738216,
            "location":"42.360080443956065, -71.05888031423092",
            "_version_": 1494752425696821200
        },
        {
            "id": "684484",
            "url": "/sport/soccer/english-league/2015/0304/684484-tottenham-v-swansea/",
            "content": "<p><strong>Tottenham 3-2&nbsp;Swansea</strong></p>\r\n<p>Tottenham got their top-four tilt back on track by overcoming Swansea 3-2 on a night when Bafetimbi Gomis&#39; collapse had those inside White Hart Lane fearing the worst.</p>\r\n<p>As play was about to restart following Nacer Chadli&#39;s wonderful, early opener, paramedics and medical staff raced onto the field to tend to the French striker after he went down.</p>\r\n<p>Hush fell on the ground where Bolton midfielder Fabrice Muamba suffered a cardiac arrest three years ago, but good news emanated from the Swansea dressing room that Gomis was fine and had not been hospitalised after feinting.</p>\r\n\r\n<blockquote align=\"center\" class=\"twitter-tweet\" lang=\"en\"><p>Good news from White Hart Lane, <a href=\"https://twitter.com/BafGomis\">@BafGomis</a> is fine and we&#39;ll provide an update as soon as possible. <a href=\"https://twitter.com/hashtag/TOTSWA?src=hash\">#TOTSWA</a></p>&mdash; Swansea City FC (@SwansOfficial) <a href=\"https://twitter.com/SwansOfficial/status/573225773135495170\">March 4, 2015</a></blockquote>\r\n\r\n\r\n<p>Garry Monk&#39;s side will have unlikely been aware of the positive news when Ki Sung-Yueng drew parity in a match which Spurs would go onto win, with second-half strikes from Ryan Mason and Andros Townsend securing the result after Gylfi Sigurdsson&#39;s late strike.</p>\r\n<p>Having exited the Europa League and lost the Capital One Cup to Chelsea in the past week, this felt like a huge win for Mauricio Pochettino&#39;s side.</p>\r\n<p>Defeat to Swansea would have seriously harmed their hopes of Champions League qualification, so Chadli&#39;s fine, cushioned volley got Spurs off to the best possible start.</p>\r\n<p>That strike was quickly forgotten, though, when Gomis collapsed - an incident which saw him leave the field on a stretcher, but was thankfully not as serious as first feared.</p>\r\n<p>It was a worrying moment Swansea recovered well from, with Ki striking home from an acute angle soon after Sigurdsson sent a free-kick off the post.</p>\r\n<p>However, there was not to be a third straight Premier League win for Swansea, with academy graduates Mason and Townsend striking for Spurs in what was for the most part a comfortable second half.</p>\r\n<p>Sigurdsson&#39;s late goal led to a nervy ending during which Hugo Lloris produced a wonderful save to ensure Spurs held on for victory - a fitting way to remember great Dave Mackay after he passed away on Monday.</p>\r\n<p>Spurs greats led a minute of applause before kick-off and the current squad wore black armbands in remembrance of one of the finest players to ever don the lillywhite shirt.</p>\r\n<p>None of the current side are a patch on Mackay but they got a win for him, opening the scoring inside seven minutes.</p>\r\n<p>Danny Rose found space on the left to send over a cross to Chadli, who showed wonderful skill and vision to hit an unorthodox cushioned volley past Lukasz Fabianski.</p>\r\n<p>It was a fine opener but it was quickly forgotten as the emotion from everyone inside White Hart Lane became one of concern as Gomis collapsed.</p>\r\n<p>The striker had four minutes of treatment before leaving the field on a stretcher - by this point conscious and wearing an oxygen mask.</p>\r\n<p>All corners of the ground applauded Gomis as he left to be replaced by Nelson Oliveira, with good news later filtering through that he would be fine.</p>\r\n<p>The first few minutes after the restart were understandably tense, with the volume only lifting when Townsend saw a low shot saved.</p>\r\n<p>By this point Swansea appeared to have refocused and Sigurdsson hit a wonderful, curled free-kick off the post.</p>\r\n<p>It was a let-off Spurs failed to heed as Swansea worked the ball back in the box and Ki stole in to prod home from an acute angle after a Jan Vertonghen mis-kick.</p>\r\n<p>The 19th-minute leveller led to a more open, end-to-end encounter, with Mason hitting at Fabianski before former Spurs full-back Kyle Naughton fizzed a low strike wide at the other end.</p>\r\n<p>Swansea&#39;s former Arsenal goalkeeper was proving a capable last line of defence for the visitors, getting a slight touch to take a clipped Christian Eriksen cross away from danger.</p>\r\n<p>A powerful Nabil Bentaleb drive was the next effort to test Fabianski, who was not to be beaten before half-time was called.</p>\r\n<p>Jonjo Shelvey saw an effort tipped over when play resumed before Ashley Williams&#39; tackle on Eriksen only put the ball into Mason&#39;s path, with the midfielder lashing home with his right foot.</p>\r\n<p>The 23-year-old&#39;s first Premier League goal swayed the match in Spurs&#39; favour, with Eriksen slicing an effort before Townsend broke at speed and cut onto his right foot, firing home when many expected him to square for Kane.</p>\r\n<p>Kyle Walker came close with an effort which deflected just wide as Spurs pushed for a fourth, with Eric Dier hauling back Oliveira on a rare Swansea attack.</p>\r\n<p>Substitute Roberto Soldado glanced a header inches wide, with the Spaniard inches away from directing home a Ben Davies cross - a missed opportunity which allowed Sigurdsson to reduce the deficit, volleying home a Jefferson Montero cross.</p>\r\n<p>The visitors pushed for an equaliser but, try as they might, there was not to be one, with Lloris tipping a Federico Fernandez header wide in stoppage time.<br />\r\n</p>",
            "title": "Tottenham maintain Euro push beating Swansea",
            "headline": "Tottenham maintain Euro push beating Swansea",
            "type": "article",
            "sub_type": "newsdocument",
            "date_created": "2015-03-04T14:25:26Z",
            "date_modified": "2015-03-04T22:08:45Z",
            "excerpt": "Tottenham got their top-four tilt back on track by overcoming Swansea 3-2 on a night when Bafetimbi Gomis' collapse had those inside White Hart Lane fearing the worst.",
            "pillar": "Sport",
            "categories": "Sport, Soccer, English, League, English Soccer League",
            "keywords": "swansea, tottenham",
            "images": "[{\"id\":\"000a406b\",\"caption\":\"Federico Fernandez of Swansea and Tottenham's Nacer Chadli contest a high ball\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a406b-60.jpg\"}]",
            "media": "[]",
            "live_listing": "[]",
            "posts": "[]",
            "thumbnail_refcode": "000a406b",
            "thumbnail_caption": "Federico Fernandez of Swansea and Tottenham's Nacer Chadli contest a high ball",
            "allow_ads": "true",
            "allow_comments": "true",
            "safe_ads": "false",
            "byline_binder_id": 0,
            "default_index_name": "English Soccer League",
            "media_count": 0,
            "rank_sport": 10,
            "rank_soccer": 6,
            "highest_rank": 5,
            "rank_english-soccer": 5,
            "rank_english-soccer-league": 5,
            "location":"51.60320259501271, -0.06642021238803864",
            "_version_": 1494752369543479300
        },
        {
            "id": "684583",
            "url": "/sport/soccer/scottish-league/2015/0304/684583-saints-swanson-sinks-celts-at-parkhead/",
            "content": "<p><strong>Celtic 0-1 St Johnstone</strong></p>\r\n<p>A magnificent strike from St Johnstone midfielder Danny Swanson inflicted a first domestic defeat of 2015 on Celtic.</p>\r\n<p>The on-loan Coventry midfielder marked his first Scottish Premiership start for Saints with a glorious first-time effort in the 54th minute to hand the visitors a 1-0 victory.</p>\r\n<p>Swanson showed brilliant technique to fire the ball into the top corner from 25 yards after Virgil van Dijk had headed David Wotherspoon&#39;s corner out of the box.</p>\r\n<p>The goal sent St Johnstone into the top six and gave Aberdeen fresh hope in the title race following their 4-0 defeat at Parkhead on Sunday.</p>\r\n<p>Celtic had the chance to move nine points clear but they remain two victories ahead of the Dons with their games in hand now used up.</p>\r\n<p>Celtic never hit the heights that had earned them 10 domestic victories in a row this year and Saints goalkeeper Alan Mannus was well worthy of his clean sheet after making some important saves.</p>\r\n<p>Celtic, who were without the injured Kris Commons and John Guidetti, started with purpose and Stuart Armstrong had a shot blocked and the recalled Anthony Stokes curled wide from a tight angle following a one-two with Leigh Griffiths.</p>\r\n<p>The chances continued to come and Saints soon got a sight of goal when the Celtic central defence failed to deal with a long ball, but Steven MacLean slice wide from 25 yards.</p>\r\n<p>Mannus tipped over Gary Mackay-Steven&#39;s first-time curler at the other end and Griffiths fired just wide from 30 yards.</p>\r\n<p>Dave Mackay and David Wotherspoon straight at Craig Gordon as the game continued in an open manner but the match went flat midway through the half.</p>\r\n<p>Celtic could not get in behind a well-organised visiting defence but Gordon was not troubled despite St Johnstone forcing themselves into attacking positions.</p>\r\n<p>There was one piece of meaningful activity just before the break when Armstrong burst towards the Saints back four but his long-range strike was pushed wide by the diving Mannus.</p>\r\n<p>Mubarak Wakaso, who spent the first part of the year on African Nations Cup duty with Ghana, made his first Celtic appearance for three months after Adam Matthews failed to appear after the interval.</p>\r\n<p>Efe Ambrose switched to right-back and winger Wakaso came in at left-back and quickly set up a good chance for Mackay-Steven, but the former Dundee United winger volleyed off target.</p>\r\n<p>St Johnstone were soon back on the attack and their pressure ultimately led to the corner from which Swanson stunned Celtic Park.</p>\r\n<p>Celtic tried to respond quickly and Stokes earned himself a yard of space on the edge of the box, but Mannus got down to hold his drive.</p>\r\n<p>And Steven Anderson had a great chance to double St Johnstone&#39;s lead moments later when David Wotherspoon&#39;s deep corner found him unmarked but the centre-back volleyed wide of the near post.</p>\r\n<p>Deila made the rest of his substitutions in the 59th minute when James Forrest and Nir Bitton replaced Mackay-Steven and Stokes, but it took the hosts a while to rediscover their attacking impetus.</p>\r\n<p>And, when they did, they found Mannus on top form. The Northern Ireland goalkeeper made an excellent parry from an Ambrose header, clasped the ball after getting down to stop Bitton&#39;s drive and then held Armstrong&#39;s powerful long-range strike.</p>\r\n<p>Chris Millar blazed well over after a decent Saints move before Celtic resumed their late surge.</p>\r\n<p>But Van Dijk headed just wide from a corner and a poor touch from Griffiths denied him the chance to finish Scott Brown&#39;s pass.<br />\r\n</p>",
            "title": "Saints' Swanson sinks Celts at Parkhead",
            "headline": "Saints' Swanson sinks Celts at Parkhead",
            "type": "article",
            "sub_type": "newsdocument",
            "date_created": "2015-03-04T21:58:34Z",
            "date_modified": "2015-03-04T22:04:16Z",
            "excerpt": "A magnificent strike from St Johnstone midfielder Danny Swanson inflicted a first domestic defeat of 2015 on Celtic.",
            "pillar": "Sport",
            "categories": "Sport, Soccer, League, Scotland, Scottish League",
            "keywords": "",
            "images": "[{\"id\":\"0004d30a\",\"caption\":\"Former Shamrock Rovers keeper Alan Mannus kept a clean sheet at Celtic Park\",\"description\":\"\",\"url\":\"//img.rasset.ie/0004d30a-60.jpg\"}]",
            "media": "[]",
            "live_listing": "[]",
            "posts": "[]",
            "thumbnail_refcode": "0004d30a",
            "thumbnail_caption": "Former Shamrock Rovers keeper Alan Mannus kept a clean sheet at Celtic Park",
            "allow_ads": "true",
            "allow_comments": "true",
            "safe_ads": "false",
            "byline_binder_id": 0,
            "default_index_name": "Scottish League",
            "media_count": 0,
            "rank_sport": 4,
            "rank_soccer": 4,
            "highest_rank": 1,
            "rank_scottish-soccer": 1,
            "rank_scottish-league": 1,
            "location":"55.84970242407504, -4.2055293917655945",
            "_version_": 1494752369543479300
        },
        {
            "id": "684342",
            "url": "/news/2015/0304/684342-ukraine-mine/",
            "content": "<p>Thirty-three miners have been confirmed dead after a coal mine blast in the rebel-held city of Donetsk near the battle front in eastern Ukraine.</p>\r\n<p>None of those trapped in the rubble survived.</p>\r\n<p>Mine officials said the explosion was most likely caused by gas and not linked to fighting at the nearby frontline in the war between Moscow-backed rebels and Ukraine government forces.</p>\r\n<p>Nevertheless, Kiev suggested the war had made the disaster worse, accusing the separatists of holding up a rescue effort by restricting access.</p>\r\n<p><img alt=\"\" src=\"https://img.rasset.ie/000a3fd1-614.jpg\" /><img alt=\"\" src=\"https://img.rasset.ie/000a3fd2-614.jpg\" /></p><p></p><p>Outside the gates of the Zasyadko mine, about 30 relatives clamoured for information about any survivors.</p>\r\n<p>The sister of one miner who was in the pit at the time of the explosion, Alexei Novoselsky, stood in tears.</p>\r\n<p>&quot;Tell me, are there survivors? Why are you concealing the truth,&quot; she said as a local rescue services employee tried to calm her.</p>\r\n<p>Eduard Dmitrenko, a miner who went down the affected shaft after the blast, said it&nbsp;was unlikely anyone would have been found alive.</p>\r\n<p>Donetsk has been the scene of heavy fighting between Moscow-backed separatist rebels, who control the area, and forces loyal to the government in Kiev.</p>\r\n<p>A ceasefire has sharply reduced the violence in the past week.</p>\r\n<p>The neighbourhood around the mine had come under artillery fire, with fragments from Grad rockets visible on surrounding roads.</p>",
            "title": "33 miners confirmed dead in Ukraine",
            "headline": "33 miners confirmed dead in Ukraine",
            "type": "article",
            "sub_type": "newsdocument",
            "date_created": "2015-03-04T07:51:40Z",
            "date_modified": "2015-03-04T22:03:34Z",
            "excerpt": "Thirty-three miners have been confirmed dead after a coal mine blast in the rebel-held city of Donetsk near the battle front in eastern Ukraine.",
            "pillar": "News",
            "categories": "News, World",
            "keywords": "mine, ukraine",
            "images": "[{\"id\":\"000a400d\",\"caption\":\"Workers involved in the rescue return to their vehicles in Donetsk\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a400d-60.jpg\"},{\"id\":\"000a3fd0\",\"caption\":\"An injured minor is treated in hospital following the blast\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3fd0-60.jpg\"},{\"id\":\"000a3f51\",\"caption\":\"Relatives of miners leave the main entrance of the Zasyadko mine\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f51-60.jpg\"}]",
            "media": "[]",
            "live_listing": "[]",
            "posts": "[]",
            "thumbnail_refcode": "000a400d",
            "thumbnail_caption": "Workers involved in the rescue return to their vehicles in Donetsk",
            "allow_ads": "true",
            "allow_comments": "false",
            "safe_ads": "false",
            "byline_binder_id": 0,
            "default_index_name": "News",
            "location":"48.0158911065136, 37.80285872519016",
            "media_count": 0,
            "rank_news": 10,
            "rank_world": 8,
            "highest_rank": 8,
            "_version_": 1494752425702064000
        },
        {
            "id": "684329",
            "url": "/news/2015/0304/684329-odonnells/",
            "content": "<p>Solicitor Brian O&#39;Donnell and his wife remain in their home in Killiney tonight, even though the deadline for them to vacate the property on the order of the High Court has expired.</p>\r\n<p>A group opposing home repossessions removed its blockade for a short time today, but put it back in place, after what it described as a person unknown tried to gain entry to the house.</p>\r\n<p>A spokesperson for the group, the self-styled&nbsp;Land League, said the O&#39;Donnells have lodged a response with the courts.</p>\r\n<p>The deadline for Mr&nbsp;O&#39;Donnell and his wife, Mary Patricia, to vacate their home expired at 4pm.</p>\r\n<p>Yesterday, the court rejected an application by the O&#39;Donnell children for an injunction to stop the repossession of the property in Killiney.</p>\r\n<p>Representatives of receivers&nbsp;last night pinned notice of trespass and to vacate on the gates of Gorse Hill in Vico Road.</p>\r\n<p><img alt=\"\" src=\"https://img.rasset.ie/000a3f1f-614.jpg\" /></p>\r\n<p>Bank of Ireland moved to serve a trespass injunction after the O&#39;Donnell children failed to secure the injunction to stop the repossession of the house.</p>\r\n<p>Judge Brian McGovern rejected that application, saying the issues raised were similar to those previously argued before the courts.</p>\r\n<p>He said Blake, Blaise, Bruce and Alexandra O&#39;Donnell had no right to grant their parents residency of the property.</p>\r\n<p>Blake O&#39;Donnell, representing his siblings, objected to requests from the bank for him to contact his father and inform him of the court&rsquo;s decision.&nbsp;</p>\r\n<p>Judge&nbsp;McGovern told him&nbsp;&quot;we can do this the easy way or make it more difficult&quot;.</p>\r\n<p>The O&#39;Donnell siblings say they are appealing the court&#39;s decision.</p><p></p><p>The self-styled Land League&rsquo;s Jerry Beades said the O&#39;Donnells responded by 4 pm to the proceedings served last night at Gorse Hill.</p>\r\n<p>They have lodged their response with the courts.&nbsp;</p>\r\n<p>He added that as proceedings by the O&rsquo;Donnell children to get a temporary injunction have not been struck out, the outcome of those proceedings will also be subject of an appeal.</p>\r\n<p>He also explained that the Land League got involved in Gorse Hill because it has brought centre stage what is happening to thousands of people around the country.</p>\r\n<p>Land League co-founder Tom Darcy said that a Supreme Court challenge to the Conveyancing Act is to go ahead and they want people around the country to row in behind it.</p>\r\n<p>A European court challenge may also take place and he said that a London firm has agreed to take a case to the European courts.</p>",
            "title": "Solicitor and wife remain at Killiney house",
            "headline": "Solicitor and wife remain at Killiney house",
            "type": "article",
            "sub_type": "newsdocument",
            "date_created": "2015-03-04T07:19:42Z",
            "date_modified": "2015-03-04T22:01:27Z",
            "excerpt": "Solicitor Brian O'Donnell and his wife remain in their home in Killiney tonight, even though the deadline for them to vacate the property on the order of the High Court has expired.",
            "pillar": "News",
            "categories": "News, Ireland, Crime and Legal",
            "keywords": "",
            "images": "[{\"id\":\"000a3f0f\",\"caption\":\"The O'Donnell family had until 4pm to vacate the gates of Gorse Hill in Vico Road\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f0f-60.jpg\"},{\"id\":\"000a3f11\",\"caption\":\"Brian O'Donnell and his wife were pursued for a debt of €71.5m by Bank of Ireland\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f11-60.jpg\"},{\"id\":\"000a3d95\",\"caption\":\"The High Court rejected an application for an injunction to stop the repossession\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3d95-60.jpg\"},{\"id\":\"000a3f7d\",\"caption\":\"Gorse Hill this morning\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f7d-60.jpg\"},{\"id\":\"000a3f12\",\"caption\":\"A summons was left nailed to the gates outside Gorse Hill last night\",\"description\":\"\",\"url\":\"//img.rasset.ie/000a3f12-60.jpg\"}]",
            "media": "[{\"id\":\"20738217\",\"type\":\"video\",\"caption\":\"Land League to continue with Killiney blockade\",\"description\":\"\",\"programme\":\"Nine News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20738217\",\"duration\":236114,\"thumbnail_refcode\":\"000a4076\"},{\"id\":\"20737773\",\"type\":\"audio\",\"caption\":\"Deadline to vacate disputed Killiney home\",\"description\":\"Ray Kennedy has the latest on the situation at solicitor Brian O'Donnell's house in Killiney Co Dublin\",\"programme\":\"Morning Ireland\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20737773\",\"duration\":132000,\"thumbnail_refcode\":\"000a3cf1\"},{\"id\":\"20737954\",\"type\":\"video\",\"caption\":\"O'Donnells have until this afternoon to leave house\",\"description\":\"\",\"programme\":\"One News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20737954\",\"duration\":122794,\"thumbnail_refcode\":\"000a3fa9\"},{\"id\":\"20738168\",\"type\":\"video\",\"caption\":\"Deadline for O'Donnell's to vacate their home expires\",\"description\":\"\",\"programme\":\"Six One News Web\",\"url\":\"https://feeds.rasset.ie/rteavgen/getplaylist/?id=20738168\",\"duration\":281833,\"thumbnail_refcode\":\"000a403d\"}]",
            "live_listing": "[]",
            "posts": "[]",
            "thumbnail_refcode": "000a3f0f",
            "thumbnail_caption": "The O'Donnell family had until 4pm to vacate the gates of Gorse Hill in Vico Road",
            "allow_ads": "true",
            "allow_comments": "false",
            "safe_ads": "false",
            "byline_binder_id": 0,
            "default_index_name": "News",
            "location":"53.26500758535152, -6.11494705080986",
            "media_count": 4,
            "rank_news": 2,
            "highest_rank": 1,
            "rank_ireland": 1,
            "rank_crime-and-legal": 3,
            "media_id": 20738217,
            "_version_": 1494752425698918400
        }
    ]
}
}